# Default values for nurzhan-hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

extra_packages:
  env:
  - name: MESSAGE
    value: "Hello World"

  - name: DB_HOST
    value: "db.fuchicorp.com"
  
  - name: DB_USER
    value: "fuchicorp-user"

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-fuchicorp-prod
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - nurzhan-hello-world.fuchicorp.com
  tls:
   - secretName: nurzhan-hello-world
     hosts:
       - nurzhan-hello-world.fuchicorp.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
